<?php

namespace DataStructure\Impl\Redis;

use Amtgard\SetQueue\DataStructure\Entry;
use Amtgard\SetQueue\DataStructure\Impl\Redis\RedisRedrivableQueue;
use PHPUnit\Framework\TestCase;
use Redis;
use function PHPUnit\Framework\assertEquals;
use function PHPUnit\Framework\assertNull;

class RedisRedrivableQueueTest extends TestCase
{
    private $queue;

    private Redis $redis;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->redis = new Redis();
        $this->redis->pconnect('127.0.0.1', 36379);
        if ($this->redis->isConnected()) {
            $this->redis->del("TEST:queue");
            $this->redis->del("TEST:redrive");
        }
        $this->queue = new RedisRedrivableQueue("TEST", $this->redis);
    }

    public function reset(): void {
        if (!$this->redis->isConnected()) {
            $this->markTestSkipped('Redis connection not established');
        } else {
            $this->redis->del("TEST:queue");
            $this->redis->del("TEST:redrive");
        }
    }

    public function testQueueFifo() {
        $this->reset();

        $entry1 = Entry::builder()->value("ENTRY1")->build();
        $entry2 = Entry::builder()->value("ENTRY2")->build();
        $entry3 = Entry::builder()->value("ENTRY3")->build();
        $this->queue->enqueue($entry1);
        $this->queue->enqueue($entry2);
        $this->queue->enqueue($entry3);
        assertEquals([$entry1], $this->queue->dequeue());
        assertEquals([$entry2], $this->queue->dequeue());
        assertEquals([$entry3], $this->queue->dequeue());
    }

    public function testRedriveRequeues()
    {
        $this->reset();

        $entry1 = Entry::builder()->value("ENTRY1")->build();
        $this->queue->enqueue($entry1);
        assertEquals([$entry1], $this->queue->dequeue());
        $null = $this->queue->dequeue();
        assertNull($null[0]);
        $this->queue->redrive();
        $entry = $this->queue->dequeue();
        assertEquals([$entry1], $entry);
    }

    public function testWhenCommit_thenNotRequeued() {
        $this->reset();

        $entry1 = Entry::builder()->value("ENTRY1")->build();
        $this->queue->enqueue($entry1);
        assertEquals([$entry1], $this->queue->dequeue());
        assertNull($this->queue->dequeue()[0]);
        $this->queue->commit($entry1);
        $this->queue->redrive();
        assertNull($this->queue->dequeue()[0]);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        if ($this->redis->isConnected()) {
            $this->redis->del("TEST:queue");
            $this->redis->del("TEST:redrive");
            $this->redis->close();
        }
    }
}