<?php

namespace Integ;

use Amtgard\SetQueue\DataStructure\Entry;
use Amtgard\SetQueue\DataStructure\HashSetFactoryInterface;
use Amtgard\SetQueue\DataStructure\Impl\Redis\RedisDataStructureConfig;
use Amtgard\SetQueue\DataStructure\Impl\Redis\RedisHashSetFactory;
use Amtgard\SetQueue\DataStructure\Impl\Redis\RedisRedrivableQueueFactory;
use Amtgard\SetQueue\DataStructure\RedrivableQueueFactoryInterface;
use Amtgard\SetQueue\DataStructure\SetQueue;
use PHPUnit\Framework\TestCase;
use Redis;
use Support\RedisTestHelper;
use function PHPUnit\Framework\assertEquals;

class RedisSetQueueTest extends TestCase
{
    use RedisTestHelper;
    private SetQueue $queue;
    private HashSetFactoryInterface $hashSetFactory;
    private RedrivableQueueFactoryInterface $redrivableQueueFactory;
    private Redis $redis;

    protected function setUp(): void
    {
        parent::setUp();
        $config = new RedisDataStructureConfig();
        $config->setConfig([
            'host' => '127.0.0.1',
            'port' => 36379,
        ]);
        $this->redis = $this->connectRedis();
        $this->flushRedisKeys($this->redis, 'TEST:set', 'TEST:queue', 'TEST:redrive');
        $this->hashSetFactory = new RedisHashSetFactory();
        $this->redrivableQueueFactory = new RedisRedrivableQueueFactory();
        $this->queue = new SetQueue("TEST", $config, $this->hashSetFactory, $this->redrivableQueueFactory);
    }

    public function reset(): void {
        if (!$this->redis->isConnected()) {
            $this->markTestSkipped('Redis connection not established');
        } else {
            $this->redis->del("TEST:set");
            $this->redis->del("TEST:queue");
            $this->redis->del("TEST:redrive");
        }
    }

    public function testQueueFifo() {
        $this->reset();

        $entry1 = Entry::builder()->key("KEY1")->value("VALUE1")->build();
        $entry2 = Entry::builder()->key("KEY2")->value("VALUE1")->build();
        $entry3 = Entry::builder()->key("KEY3")->value("VALUE1")->build();
        $this->queue->enqueue($entry1);
        $this->queue->enqueue($entry2);
        $this->queue->enqueue($entry3);
        assertEquals([$entry1], $this->queue->dequeue());
        assertEquals([$entry2], $this->queue->dequeue());
        assertEquals([$entry3], $this->queue->dequeue());
    }

    public function testRedriveRequeues()
    {
        $this->reset();

        $entry1 = Entry::builder()->key("KEY1")->value("VALUE1")->build();
        $this->queue->enqueue($entry1);
        assertEquals([$entry1], $this->queue->dequeue());
        assertEquals([], $this->queue->dequeue());
        $this->queue->redrive();
        assertEquals([$entry1], $this->queue->dequeue());
    }

    public function testWhenCommit_thenNotRequeued() {
        $this->reset();

        $entry1 = Entry::builder()->key("KEY1")->value("VALUE1")->build();
        $this->queue->enqueue($entry1);
        assertEquals([$entry1], $this->queue->dequeue());
        assertEquals([], $this->queue->dequeue());
        $this->queue->commit($entry1);
        $this->queue->redrive();
        assertEquals([], $this->queue->dequeue());
    }

    public function testStoreRetrieve_MixedObject() {
        $this->reset();

        $stdo = new \stdClass();
        $stdo->f1 = "f1";
        $stdo->f2 = "f2";
        $stdo->f3 = ["f3", "f4"];

        $entry1 = Entry::builder()->key("KEY1")->value($stdo)->build();
        $this->queue->enqueue($entry1);

        $response = $this->queue->dequeue();
        assertEquals([$entry1], $response);
        assertEquals([], $this->queue->dequeue());
        $this->queue->commit($entry1);
        $this->queue->redrive();
        assertEquals([], $this->queue->dequeue());
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        if ($this->redis->isConnected()) {
            $this->redis->del("TEST:set");
            $this->redis->del("TEST:queue");
            $this->redis->del("TEST:redrive");
            $this->redis->close();
        }
    }
}