<?php

namespace DataStructure;

use Amtgard\Interface\HashSetInterface;use Amtgard\Interface\RedrivableQueueInterface;use Amtgard\SetQueue\DataStructure\DataStructureConfig;use Amtgard\SetQueue\DataStructure\Entry;use Amtgard\SetQueue\DataStructure\HashSetFactoryInterface;use Amtgard\SetQueue\DataStructure\RedrivableQueueFactoryInterface;use Amtgard\SetQueue\DataStructure\SetQueue;use Phake;use PHPUnit\Framework\TestCase;

class SetQueueTest extends TestCase
{

    private SetQueue $setQueue;

    private HashSetFactoryInterface $mockSetFactory;

    private RedrivableQueueFactoryInterface $mockRedrivableQueueFactory;

    private HashSetInterface $mockSet;

    private RedrivableQueueInterface $mockQueue;

    private DataStructureConfig $config;

    protected function beforeEach(): void {
        Phake::reset($this->mockSetFactory);
        Phake::reset($this->mockRedrivableQueueFactory);
        Phake::when($this->mockSetFactory)->create($this->config, "SETQUEUE_NAME")->thenReturn($this->mockSet);
        Phake::when($this->mockRedrivableQueueFactory)->create($this->config, "SETQUEUE_NAME")->thenReturn($this->mockQueue);

        $entry = Entry::builder()->key("KEY")->value("VALUE")->build();

        Phake::when($this->mockSet)->add($entry)->thenReturn("VALUE");
        Phake::when($this->mockSet)->contains($entry)->thenReturn(true);
        Phake::when($this->mockSet)->remove($entry)->thenReturn("VALUE");
        Phake::when($this->mockSet)->get($entry)->thenReturn("VALUE");
        Phake::when($this->mockSet)->getList([$entry])->thenReturn(["VALUE"]);

        Phake::when($this->mockQueue)->enqueue($entry);
        Phake::when($this->mockQueue)->dequeue(1)->thenReturn([$entry]);
        Phake::when($this->mockQueue)->commit();
        Phake::when($this->mockQueue)->redrive();

    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->config = Phake::mock(DataStructureConfig::class);
        $this->mockSet = Phake::mock(HashSetInterface::class);
        $this->mockQueue = Phake::mock(RedrivableQueueInterface::class);
        $this->mockSetFactory = Phake::mock(HashSetFactoryInterface::class);
        $this->mockRedrivableQueueFactory = Phake::mock(RedrivableQueueFactoryInterface::class);

        $this->beforeEach();
        $this->setQueue = new SetQueue("SETQUEUE_NAME", $this->config, $this->mockSetFactory, $this->mockRedrivableQueueFactory);
    }

    public function testGetName() {
        $this->beforeEach();
        self::assertEquals("SETQUEUE_NAME", $this->setQueue->getName());
    }

    public function testEnqueueDequeue() {
        $this->beforeEach();

        $entry = Entry::builder()->key("KEY")->value("VALUE")->build();
        $this->setQueue->enqueue($entry);
        $response = $this->setQueue->dequeue();
        self::assertEquals([$entry], $response);
    }

}